### PR TITLE
Gamma Market Visibility

### LINKED ISSUE #332: PBS Market items fail to show on remote markets
Command `MarketItemsInRange` ends up calling `IMarketOrderRepository.GetAllByDefinition` which produces the following query.

```sql
SELECT marketitems.marketitemid, marketitems.marketeid, marketitems.itemeid, marketitems.itemdefinition, marketitems.submittereid, 
marketitems.submitted, marketitems.duration, marketitems.isSell, marketitems.price, marketitems.quantity, 
marketitems.usecorporationwallet, marketitems.isvendoritem, marketitems.formembersof FROM marketitems 
INNER JOIN entities as childentity on (marketitems.marketeid=childentity.eid) 
INNER JOIN entities parent on (childentity.eid=parent.eid) 
INNER JOIN zoneentities on (parent.parent=zoneentities.eid) 
INNER JOIN zones on (zoneentities.zoneid=zones.id) where itemdefinition = @definition and zones.enabled=1
```

A key problem for PBS is that the terminals are not appearing as ZoneEntities in the zoneentities table.  Thus no orders.

impl hint: PBS are zoneuserentities, not zoneentities

### PR DESCRIPTION
**Pull request by MikeJeffers**
Requires: https://github.com/OpenPerpetuum/PerpetuumServer/pull/333 (as a pre-req for any gamma market stuff)
Closes: #332 
The jury is still out on how it used to be.  Existing code suggests that all Gamma orders are invisible remotely.
But let's enhance that:
This PR now features remote market order visibility for Gamma bases that a character can *see* (meaning the base is visible to them via the `PBSDockingBaseVisibility` value)

This also increase the fetch speed on the `MarketItemsInRange` command because it is not doing 4 joins like the `GetAllByDefinition` method, and it is not filtering the list after the fact in memory cleaning out training orders and corp order logic.
It does have an initial query for markets (in memory), but I chose to cache this as remote market browsing generates a lot of rapid requests, its worth caching just for a few minutes.

Also some related refactoring to encapsulate the visibility logic and reduce the frequency of the corp role query in that extension method.

### CODE REVIEW

**Comment by naHrej** [comment]
The market displays remotely after the terminal becomes visible only after logging the character off and back on.  I'm not versed enough in the client side of things yet to make anything but guesses as to why that is - I'm making the assumption though that it's to do with data not being pushed to the client for this purpose.

This PR does address the issue of visibility though, the remote market is not visible unless the terminal is.

File: src/Perpetuum/Services/MarketEngine/MarketHandler.cs [hunk 1]
```diff
@@ -81,7 +84,17 @@ public IEnumerable<long> GetAllDefaultMarketsEids(bool includeGamma = false, boo
...
+
+        public IEnumerable<long> GetAllVisibleMarketsFor(Character c)
+        {
+            return _visibleMarkets.Get(c.Eid.ToString(), () =>
+            {
+                return _marketPriceCollectors.Values
+                .Where(pc => !pc.IsTrainingMarket)
+                .Where(pc => pc.IsVisible(c))
+                .Select(pc => pc.Market.Eid);
+            }, TimeSpan.FromMinutes(2));
```
Comment (MikeJeffers) [inline src/Perpetuum/Services/MarketEngine/MarketHandler.cs:96]: @TheAntiDean this is why the change did not appear immediately ;)
A natural tradeoff with caching, eventual consistency.

Or at least I don't *think* the character should have to logoff for them to see a change, only that the cached set of markets needs to expire.

**Review by naHrej — APPROVED** [review]
Retested and confirmed that the market does appear on the remote list for a character newly able to see the market after a period of time. Does not appear on the remote market list for characters who should not be able to see it.
