### PR TITLE
Mission expiration bug fix

### LINKED ISSUE #133: Robustify expired mission handling
Make mission expiration logic more robust.  
Server can get into a state where expired missions will continuously throw this:
```
[13:01:35] INF mission expired: guid:5e2d9c29-19e3-485d-b8ae-5bb62d192bca characterID:353 missionID:1169 expire:2/27/2020 12:27:43 PM current targetOrder:0 title:missiontemplate_random_geoscanning_01
[13:01:35] INF mission expired. guid:5e2d9c29-19e3-485d-b8ae-5bb62d192bca characterID:353 missionID:1169 expire:2/27/2020 12:27:43 PM current targetOrder:0 title:missiontemplate_random_geoscanning_01
[13:01:35] INF sending mission update to zone:5 isFinished:True
[13:01:35] ERR 
Exception Found:
Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: Perpetuum
Stacktrace:    at Perpetuum.Services.MissionEngine.Missions.MissionStandingChangeCalculator.VisitRandomMission(RandomMission randomMission)
   at Perpetuum.Services.MissionEngine.Missions.MissionInProgress.WriteFailure()
   at Perpetuum.Services.MissionEngine.Missions.MissionInProgress.OnMissionFailure(Command command, MissionProcessor missionProcessor, ErrorCodes errorToInfo)
   at Perpetuum.Services.MissionEngine.AdministratorObjects.MissionAdministrator.MissionExpireCycle()
```

### PR DESCRIPTION
**Pull request by MikeJeffers**
Fixes #133

### CODE REVIEW

File: src/Perpetuum/Services/MissionEngine/Missions/MissionInProgress.cs [hunk 1]
```diff
@@ -1461,10 +1461,10 @@ public double GetDifficultyReward
 
         public double GetParticipantBonusModifier()
         {
-            return computeParticipantBonusMultiplier(this._participants.Count);
+            return ComputeParticipantBonusMultiplier(GetParticipants().Count);
```
Comment (MikeJeffers) [inline src/Perpetuum/Services/MissionEngine/Missions/MissionInProgress.cs:1465]: This is the actual fix, rest is refactoring and properly accessing the _participants collection via its getter

**Review by nref-dan — COMMENTED** [review]
Why doesn't this just use a `Lazy<T>` initialiser?

**Comment by MikeJeffers** [comment]
> 
> 
> Why doesn't this just use a `Lazy<T>` initialiser?

Good point, not sure why that wasn't used here to begin with..

File: src/Perpetuum/Services/MissionEngine/Missions/MissionInProgress.cs [hunk 2]
```diff
@@ -92,6 +93,7 @@ public MissionInProgress(Mission mission,IStandingHandler standingHandler,IProdu
             _standingHandler = standingHandler;
             _productionDataAccess = productionDataAccess;
             _zoneManager = zoneManager;
+            _participants = new Lazy<HashSet<Character>>(LoadParticipantsFromDb);
```
Comment (nref-dan) [inline src/Perpetuum/Services/MissionEngine/Missions/MissionInProgress.cs]: Please put this inline on the variable declaration as
`private Lazy<HashSet<Character>> _participants = new Lazy<HashSet<Character>>(() => LoadParticipantsFromDb());`

As a response to both your question and mine, it's entirely possible that this call may fail once, then succeed subsequently. In this case, Lazy initialisation is to be avoided because the initialisation call is only made *once*. If it fails, it will not be called again. It's worth checking this by eye before merging this change, because Lazy<T> initialisation ought to be preferred in all other scenarios.

**Review by nref-dan — CHANGES_REQUESTED** [review]

File: src/Perpetuum/Services/MissionEngine/Missions/MissionInProgress.cs (hunk 2 above)
Comment (MikeJeffers) [reply src/Perpetuum/Services/MissionEngine/Missions/MissionInProgress.cs]: Actually, this is a bit weird.  It looks more like they wanted this to be DB-backed at every "write":
```cs
        public void AddParticipant(Character doerCharacter)
        {
            if (!spreadInGang) return;
            
            if (!IsParticipant(doerCharacter))
            {
                WriteParticipant(missionGuid, doerCharacter);
                _participants = null;
            }
        }

        public void ForceAddParticipant()
        {
            WriteParticipant(missionGuid, character);
            _participants = null;
        }


        public static void WriteParticipant(Guid missionGuid, Character doerCharacter)
        {
            if (missionGuid == Guid.Empty || doerCharacter == Character.None) return;

            Db.Query().CommandText("missionAddParticipant")
                .SetParameter("@missionGuid", missionGuid)
                .SetParameter("@characterId", doerCharacter.Id)
                .Execute();
        }
```
It is null'ing out the collection completely, and was using the `LazyIntializer` in that Get method which would re-fetch from the DB.
So actually my change is broken X.X  I might rollback to how they had it.

Comment (MikeJeffers) [reply src/Perpetuum/Services/MissionEngine/Missions/MissionInProgress.cs]: Unless there is a way to get the initializer to re-fire, but from reading up on the Lazy<T> docs I wasn't seeing a way with this alone.  In fact the `LazyInitializer` lets you call and use it as you like, which makes more sense knowing that they drop the state held in memory as soon as any participant joins the mission.

Comment (nref-dan) [reply src/Perpetuum/Services/MissionEngine/Missions/MissionInProgress.cs]: Madness! Why not just update the hashset in memory? Unless it’s expecting out of sync, external writes?

Revert this for now. This system likely needs refactoring as a whole.

File: src/Perpetuum/Services/MissionEngine/Missions/MissionInProgress.cs [hunk 3]
```diff
@@ -1461,10 +1462,10 @@ public double GetDifficultyReward
 
         public double GetParticipantBonusModifier()
         {
-            return computeParticipantBonusMultiplier(this._participants.Count);
+            return ComputeParticipantBonusMultiplier(GetParticipants().Count);
         }
 
-        private double computeParticipantBonusMultiplier(int paricipantCount)
+        private double ComputeParticipantBonusMultiplier(int paricipantCount)
```
Comment (nref-dan) [inline src/Perpetuum/Services/MissionEngine/Missions/MissionInProgress.cs]: Not a bug, but a typo

File: src/Perpetuum/Services/MissionEngine/Missions/MissionInProgress.cs (hunk 1 above)
Comment (nref-dan) [reply src/Perpetuum/Services/MissionEngine/Missions/MissionInProgress.cs:1465]: Fix is good. This entire class needs refactoring and restructuring though; a job for ol' Ron I think.

**Review by nref-dan — APPROVED** [review]
Just sort that typo out before you push and sorted :)
