### PR TITLE
Staging PBS base: expires + other unique rules

### LINKED ISSUE #371: PBS error on decon
Delete error on terminal deconstruct/destruction
```
[18:19:41] INF  >>>>>>    docking base SQL DELETE   STOP 
[18:19:41] INF Entity deleted. eid:xxxdef_system_container (578) o:xxxp:xxxh:100 n: q:1 r:False
[18:19:41] ERR 
Exception Found:
Type: Perpetuum.PerpetuumException
Message: Exception of type 'Perpetuum.PerpetuumException' was thrown.
Source: Perpetuum
Stacktrace:    at Perpetuum.Guard.ThrowIfTrue(Boolean value, Func`1 exceptionFactory)
   at Perpetuum.Guard.ThrowIfEqual[T](T actual, T expected, ErrorCodes error, Action`1 exceptionAction)
   at Perpetuum.EntityFramework.EntityRepository.Delete(Entity entity)
   at Perpetuum.EntityFramework.EntityRepository.Delete(Entity entity)
   at Perpetuum.EntityFramework.EntityRepository.Delete(Entity entity)
   at Perpetuum.Zones.ZoneEntityRepositories.ZoneUnitService.RemoveUserUnit(Unit unit)
   at Perpetuum.Zones.PBS.PBSHelper.OnPBSObjectRemovedFromZone[T](T removedUnit, IZone zone)
   at Perpetuum.Data.Db.<>c__DisplayClass6_0.<CreateTransactionAsync>b__0()
   at System.Threading.Tasks.Task.Execute()

Error = SQLDeleteError
```

### LINKED ISSUE #404: "Staging" PBS terminal (T0)
A gamma PBS terminal that can:
- anchor in red zones
- anchor with *less* slope restrictions, or smaller footprint check (maybe/debatable - red zone non-terraformable)
- Gamma only (not T0 islands!)
- Not count towards Island/corp totals
- Expire over some number of days/hours
- 1 or 0 reinforce cycles (TBD design question)
- Subject to different set of keepout ranges (from npc base, from teleports, from terminals - including other T0 terminals)
- 0 bandwidth and not be connected to, or allow the construction of other buildings of any kind. (`bandwidth_capacity`, `network_node_range`, ... definitionconfig)

### PR DESCRIPTION
**Pull request by MikeJeffers**
Closes: #404 
Fixes: #371 (this terminal made this easy to test and abundantly troublesome if not fixed)
This is adding a special PBS base that will not behave with *any* of the existing rules about PBS structures.
The issue details the requirements

### CODE REVIEW

File: src/Perpetuum/Services/ProductionEngine/Facilities/ProductionFacility.cs [hunk 1]
```diff
@@ -255,7 +255,7 @@ protected void CreateSystemStorage()
 
         protected void RemoveStorage()
         {
-            Repository.DeleteTree(StorageEid);
+            Repository.DeleteTreeButNotRoot(StorageEid);
```
Comment (MikeJeffers) [inline src/Perpetuum/Services/ProductionEngine/Facilities/ProductionFacility.cs:258]: This fixes #371 
On death/deconstruction the facility system-storages would be deleted as children on the parent, AND by deleting itself and the tree of items it may contain.
2 Delete calls, where the next fails and breaks the transaction.  
The base disappears from memory, but not from the DB and will reappear on restart!

**Review by jeffmaley — APPROVED** [review]
This looks good to me.

File: src/Perpetuum.Bootstrapper/PerpetuumBootstrapper.cs [hunk 2]
```diff
@@ -1122,6 +1123,7 @@ private void RegisterEntities()
                 ByCategoryFlags<PublicCorporationHangarStorage>(CategoryFlags.cf_public_corporation_hangar_storage);
                 ByCategoryFlags<DockingBase>(CategoryFlags.cf_public_docking_base);
                 ByCategoryFlags<PBSDockingBase>(CategoryFlags.cf_pbs_docking_base);
+                ByName<ExpiringPBSDockingBase>("def_pbs_expiring_docking_base");
```
Comment (MikeJeffers) [inline src/Perpetuum.Bootstrapper/PerpetuumBootstrapper.cs]: TODO: use the definitionname you inserted you dummy!
