### PR TITLE
AOE bot-death damage radius + LOS fix for 0 distance

### LINKED ISSUE #140: IsInLineOfSight breaks at 0 distance
Fortunately my debugger caught this before consuming the error (this happens inside some task I presume)
Throws when direction vector properties are NaN, so something generating the direction vector fails.
Produced when killing npc on beta (explosion damage?) 
```
System.OverflowException
  HResult=0x80131516
  Message=Arithmetic operation resulted in an overflow.
  Source=Perpetuum
  StackTrace:
   at Perpetuum.Zones.LineOfSight.IsInLineOfSight(IZone zone, Vector3 origin, Vector3 direction, Single distance, Boolean ballistic) in C:\Users\Unavailable\Documents\OpenPerpetuum\PerpetuumServer\src\Perpetuum\Zones\LineOfSight.cs:line 113
   at Perpetuum.Zones.LineOfSight.IsInLineOfSight(IZone zone, Unit sourceUnit, Unit targetUnit, Boolean ballistic) in C:\Users\Unavailable\Documents\OpenPerpetuum\PerpetuumServer\src\Perpetuum\Zones\LineOfSight.cs:line 61
   at Perpetuum.Zones.ZoneExtensions.DoAoeDamage(IZone zone, IBuilder`1 damageBuilder) in C:\Users\Unavailable\Documents\OpenPerpetuum\PerpetuumServer\src\Perpetuum\Zones\ZoneExtensions.cs:line 176
   at Perpetuum.Units.Unit.<>c__DisplayClass125_0.<DoExplosion>b__0(Task t) in C:\Users\Unavailable\Documents\OpenPerpetuum\PerpetuumServer\src\Perpetuum\Units\Unit.cs:line 482
   at System.Threading.Tasks.Task.Execute()
```

Needs more research as to the originating issue with the bad vector being passed in.

### PR DESCRIPTION
**Pull request by MikeJeffers**
Ok should be separate PR's but npcs on the same tile was where we see this occurring most so it was easier to test and fix while working on the other issue.

The srf-area-to-falloff-range curve is bespoke but continuous and smooth for the ranges of bot sizes and srf-area modifying equipment.  Because HMechs are significantly larger, it was no longer possible to keep this linear without some very large consequences.

The output is bounded to allow hard floors/ceilings to prevent runaway explosion sizes with future/potential srf-areas to come.

The details for the data used to interpolate this curve are in the balance team design docs, the specifics of which can be debated there.

Closes #140 
Because direction at 0 distance can't be computed, let's handle that case.  
Debatable point: Now that it is not throwing exceptions, should it result in a valid hit or miss?

### CODE REVIEW

File: src/Perpetuum/Units/Unit.cs [hunk 1]
```diff
@@ -482,9 +482,21 @@ protected virtual void DoExplosion()
...
+        /// <summary>
+        /// Fitted curve to achieve desired explosion distances for bots of certain sizes by class
+        /// Ensures output will be bounded and that arbitrary input will not result in error or undesired output
+        /// </summary>
+        /// <param name="x">SignativeRadius of bot</param>
+        /// <returns>Radius in number of tiles (10m)</returns>
+        private double SigRadiusToExplosionRadius(double x)
+        {
+            x = x.Clamp(3.0, 40.0);
+            return (-3.336453 + 1.617863 * x - 0.09721877 * (x * x) + 0.002064723 * (x * x * x)).Clamp(1.0, 30.0);
```
Comment (nref-dan) [inline src/Perpetuum/Units/Unit.cs:494]: Can we put some meaningful names to these numbers please? :)

i.e. What does -3.336453 represent?

File: src/Perpetuum/Zones/LineOfSight.cs [hunk 2]
```diff
@@ -98,8 +98,20 @@ public static LOSResult IsInLineOfSight(this IZone zone, Position start, Unit ta
         }
 
         [NotNull]
-        private static LOSResult IsInLineOfSight(IZone zone,Vector3 origin,Vector3 direction,float distance,bool ballistic)
+        private static LOSResult IsInLineOfSight(IZone zone, Vector3 origin, Vector3 direction, float distance, bool ballistic)
         {
+            if (distance == 0.0)
```
Comment (nref-dan) [inline src/Perpetuum/Zones/LineOfSight.cs]: You're going to need an "Approximately Equal" function. Due to floating point error this might not be true, but is instead virtually zero i.e. 0.000000000000000000123

Something like this:
```
    public static bool IsApproximatelyEqual(this float left, float right, float precision = 1e-7f)
    {
      var result = Math.Abs(left - right);
      return result <= precision;
    }
```

You would then call it like `if (distance.IsApproximatelyEqual(0, 0.1))` to check if the value is 0 to within a margin of error of 0.1. i.e. 0.05 would be true, 0.09 would be true, 0.1 **would also be true**, 0.10001 would be false

**Review by nref-dan — CHANGES_REQUESTED** [review]
Just needs the numbers giving some meaningful descriptions, and the approximately equals extension

File: src/Perpetuum/Zones/LineOfSight.cs (hunk 2 above)
Comment (MikeJeffers) [reply src/Perpetuum/Zones/LineOfSight.cs]: Yes I was considering an equal within epsilon, but I think the absolute boundary of this case is when distance (or magnitude of direction vector) is 0, prior vector math makes its components NaN and thats where things go wrong.
As soon as there is a distance, there is a direction, and seems to be ok, so long as it is not absolutely 0

But I agree, it feels safer to just get a bit of a margin, in case other operations still turn out 0->NaN'ing vectors, but distance isn't exactly 0.

File: src/Perpetuum/Units/Unit.cs (hunk 1 above)
Comment (MikeJeffers) [reply src/Perpetuum/Units/Unit.cs:494]: This unfortunately is a fitted curve to some key explosion radius outcomes we wanted across different surface sizes.  The coefficients and constants are not going to have much meaning on their own... (at least not that I can articulate)
Which makes this a non-ideal solution to a very undesirable problem as the result of some key balance changes.

**Comment by MikeJeffers** [comment]
As it turns out there is a IsZero check that uses the type's Epsilon, but I added your extension to allow greater control for thresholds and equality checking other values easier.

**Review by nref-dan — APPROVED** [review]
